disabled_rules:
- trailing_whitespace
- mark #

nesting:
  type_level:
    warning: 4
    error: 6
  

line_length:
- 250 # warning
- 300 #error
identifier_name:
 max_length:
    warning: 45
    error: 60
 min_length:
    warning: 1
    
