# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ToDoListYa' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ToDoListYa
  pod 'SwiftLint'

  target 'ToDoListYaTests' do
    inherit! :search_paths
    # Pods for testing
  end

  #target 'ToDoListYaUITests' do
    # Pods for testing
  #end

end
